theme: "PaperMod"
languageCode: en-us
title: jessyprovencher.xyz
baseURL: https://jessyprovencher.xyz/

# enable options
enableEmoji: true
enableRobotsTXT: true

# build option
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

languages:
  en:
    languageName: ":us:"
    languageAltTitle: English
    weight: 1
  fr:
    languageName: ":fr:"
    languageAltTitle: French
    weight: 2
    # profile mode
    profileMode:
      enabled: true
      title: jessyprovencher.xyz
      subtitle: "Lien rapides"
      imageUrl: "https://avatars.githubusercontent.com/u/70674444"
      imageWidth: 160
      imageHeight: 160
      imageTitle: Jessy Provencher
    # menu options
    menu:
      main:
        - identifier: posts
          name: articles
          url: /posts/
          weight: 10
        - identifier: tags
          name: mots-clés
          url: /tags/
          weight: 20
        - identifier: categories
          name: catégories
          url: /categories/
          weight: 30
        - identifier: search
          name: recherche
          url: /search/
          weight: 40

params:
  env: production
  author: Jessy Provencher
  title: jessyprovencher.xyz
  description: "jessyprovencher's website"
  keywords: [Jessy Provencher, jessyprovencher, website, portfolio]
  # images: ["<link or path of image for opengraph, twitter-cards>"]

  # theme
  defaultTheme: auto
  disableThemeToggle: false
  
  # show options
  showReadingTime: true
  showBreadCrumbs: true
  showPostNavLinks: true
  showShareButtons: false
  showCodeCopyButtons: true

  # disable options
  comments: false
  disableScrollToTop: false
  disableSpecial1stPost: false

  # hide options
  hideMeta: false
  hideSummary: false

  # table of contents (toc)
  showToc: true
  tocOpen: false

  assets:
    disableHLJS: true
    disableFingerprinting: true
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-16x16.png"
    apple_touch_icon: "/apple-touch-icon.png"
    safari_pinned_tab: "/safari-pinned-tab.svg"

  # header
  label:
    text: "jessyprovencher.xyz"

  # profile mode
  profileMode:
    enabled: true
    title: jessyprovencher.xyz
    subtitle: "Quick links"
    imageUrl: "/avatar.jpg"
    imageWidth: 160
    imageHeight: 160
    imageTitle: Jessy Provencher

  # profile icons
  profileIcons:
    - name: rss
      url: "/index.xml"
    #- name: cv
    #  url: "todo"
    - name: github
      url: "https://github.com/jessyprovencher"
    - name: linkedin
      url: "https://ca.linkedin.com/in/jessy-provencher"
    - name: paypal
      url: "https://www.paypal.me/jessyprovencher"

  # cover
  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true

  # edit post
  editPost:
    URL: "https://github.com/jessyprovencher/jessyprovencher-xyz/tree/master/content"
    appendFilePath: true

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# taxonomies
taxonomies:
  tag: tags
  category: categories
  
# menu options
menu:
  main:
    - identifier: posts
      name: posts
      url: /posts/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: categories
      name: categories
      url: /categories/
      weight: 30
    - identifier: search
      name: search
      url: /search/
      weight: 40

# outputs
outputs:
  home:
    - HTML
    - RSS
    - JSON
